# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dkinput.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(359, 310)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginDialog.sizePolicy().hasHeightForWidth())
        LoginDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(LoginDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Bank_Name = QtWidgets.QLineEdit(LoginDialog)
        self.Bank_Name.setObjectName("Bank_Name")
        self.gridLayout_2.addWidget(self.Bank_Name, 1, 1, 1, 1)
        self.Loan_ID = QtWidgets.QLineEdit(LoginDialog)
        self.Loan_ID.setObjectName("Loan_ID")
        self.gridLayout_2.addWidget(self.Loan_ID, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(LoginDialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(LoginDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(LoginDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.Loan_Amount = QtWidgets.QDoubleSpinBox(LoginDialog)
        self.Loan_Amount.setMinimum(0.01)
        self.Loan_Amount.setMaximum(999999999999.0)
        self.Loan_Amount.setObjectName("Loan_Amount")
        self.gridLayout_2.addWidget(self.Loan_Amount, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.label = QtWidgets.QLabel(LoginDialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.Owners = QtWidgets.QTextEdit(LoginDialog)
        self.Owners.setObjectName("Owners")
        self.verticalLayout_2.addWidget(self.Owners)
        self.gridLayout.addLayout(self.verticalLayout_2, 5, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.OB = QtWidgets.QPushButton(LoginDialog)
        self.OB.setObjectName("OB")
        self.verticalLayout.addWidget(self.OB)
        self.EB = QtWidgets.QPushButton(LoginDialog)
        self.EB.setObjectName("EB")
        self.verticalLayout.addWidget(self.EB)
        self.gridLayout.addLayout(self.verticalLayout, 5, 4, 1, 1)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "输入"))
        self.label_8.setText(_translate("LoginDialog", "贷款号："))
        self.label_6.setText(_translate("LoginDialog", "支行名："))
        self.label_2.setText(_translate("LoginDialog", "总额度："))
        self.label.setText(_translate("LoginDialog", "输入贷款持有者（每行一位）："))
        self.OB.setText(_translate("LoginDialog", "应用"))
        self.EB.setText(_translate("LoginDialog", "取消"))
