# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dkupd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(242, 123)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginDialog.sizePolicy().hasHeightForWidth())
        LoginDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(LoginDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Date = QtWidgets.QDateEdit(LoginDialog)
        self.Date.setObjectName("Date")
        self.gridLayout_2.addWidget(self.Date, 2, 1, 1, 1)
        self.Amount = QtWidgets.QDoubleSpinBox(LoginDialog)
        self.Amount.setMinimum(0.01)
        self.Amount.setMaximum(999999999999.0)
        self.Amount.setObjectName("Amount")
        self.gridLayout_2.addWidget(self.Amount, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(LoginDialog)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.nDate = QtWidgets.QCheckBox(LoginDialog)
        self.nDate.setObjectName("nDate")
        self.gridLayout_2.addWidget(self.nDate, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(LoginDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.ID = QtWidgets.QLineEdit(LoginDialog)
        self.ID.setObjectName("ID")
        self.gridLayout_2.addWidget(self.ID, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 5, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.OB = QtWidgets.QPushButton(LoginDialog)
        self.OB.setObjectName("OB")
        self.horizontalLayout.addWidget(self.OB)
        self.EB = QtWidgets.QPushButton(LoginDialog)
        self.EB.setObjectName("EB")
        self.horizontalLayout.addWidget(self.EB)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 3, 1, 1)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "输入"))
        self.label.setText(_translate("LoginDialog", "发放金额："))
        self.nDate.setText(_translate("LoginDialog", "发放日期："))
        self.label_2.setText(_translate("LoginDialog", "发放编号："))
        self.OB.setText(_translate("LoginDialog", "确定"))
        self.EB.setText(_translate("LoginDialog", "取消"))
