# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhupdzp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(524, 72)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginDialog.sizePolicy().hasHeightForWidth())
        LoginDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(LoginDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Balance = QtWidgets.QDoubleSpinBox(LoginDialog)
        self.Balance.setMaximum(999999999999.0)
        self.Balance.setObjectName("Balance")
        self.gridLayout_2.addWidget(self.Balance, 0, 3, 1, 1)
        self.Overdraft = QtWidgets.QDoubleSpinBox(LoginDialog)
        self.Overdraft.setMaximum(999999999999.0)
        self.Overdraft.setObjectName("Overdraft")
        self.gridLayout_2.addWidget(self.Overdraft, 1, 3, 1, 1)
        self.nBalance = QtWidgets.QCheckBox(LoginDialog)
        self.nBalance.setObjectName("nBalance")
        self.gridLayout_2.addWidget(self.nBalance, 0, 2, 1, 1)
        self.nOverdraft = QtWidgets.QCheckBox(LoginDialog)
        self.nOverdraft.setObjectName("nOverdraft")
        self.gridLayout_2.addWidget(self.nOverdraft, 1, 2, 1, 1)
        self.Bank_Name = QtWidgets.QLineEdit(LoginDialog)
        self.Bank_Name.setObjectName("Bank_Name")
        self.gridLayout_2.addWidget(self.Bank_Name, 0, 1, 1, 1)
        self.nBank_Name = QtWidgets.QCheckBox(LoginDialog)
        self.nBank_Name.setObjectName("nBank_Name")
        self.gridLayout_2.addWidget(self.nBank_Name, 0, 0, 1, 1)
        self.nOpening_Date = QtWidgets.QCheckBox(LoginDialog)
        self.nOpening_Date.setObjectName("nOpening_Date")
        self.gridLayout_2.addWidget(self.nOpening_Date, 1, 0, 1, 1)
        self.Opening_Date = QtWidgets.QDateEdit(LoginDialog)
        self.Opening_Date.setObjectName("Opening_Date")
        self.gridLayout_2.addWidget(self.Opening_Date, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 5, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.OB = QtWidgets.QPushButton(LoginDialog)
        self.OB.setObjectName("OB")
        self.verticalLayout.addWidget(self.OB)
        self.EB = QtWidgets.QPushButton(LoginDialog)
        self.EB.setObjectName("EB")
        self.verticalLayout.addWidget(self.EB)
        self.gridLayout.addLayout(self.verticalLayout, 5, 4, 1, 1)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "输入"))
        self.nBalance.setText(_translate("LoginDialog", "余额："))
        self.nOverdraft.setText(_translate("LoginDialog", "透支额："))
        self.nBank_Name.setText(_translate("LoginDialog", "支行名："))
        self.nOpening_Date.setText(_translate("LoginDialog", "开户日期："))
        self.OB.setText(_translate("LoginDialog", "确定"))
        self.EB.setText(_translate("LoginDialog", "取消"))
